version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - ../:/usr/src/app
      - ../compartilhado:/usr/src/app/compartilhado

